org.gradle.jvmargs=-Xmx3G
enabled_platforms=fabric,neoforge
minecraft_version=1.21.4
parchment_version=1.21.4:2024.12.29

# Forge Properties
neo_loader_version=2
neoforge_version=21.4.47-beta
# Fabric Properties
loader_version=0.16.9

# Mod Properties
mod_version=1.0.2_custom
maven_group=io.github.flemmli97
archives_base_name=villagertrades

# Dependencies
fabric_version=0.114.0+1.21.4
fabric_permissions_api=0.2-SNAPSHOT
